AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  CoursesLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: FetchInstructorCoursesGivenInstructorName
      Handler: courses_lambda/index.handler
      Runtime: nodejs18.x  
      CodeUri: courses_lambda/
      MemorySize: 3000
      Timeout: 45

  InstructorsLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: FetchInstructorNamesForGivenMajorAndTerm
      Handler: instructors_lambda/index.handler
      Runtime: nodejs18.x 
      CodeUri: instructors_lambda/
      MemorySize: 3000
      Timeout: 45

  AddCourseTrackingLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: AddCourseTrackingLambdaFunction
      Handler: app.main
      Runtime: python3.11
      CodeUri: add_tracking_lambda/
      MemorySize: 3000
      Timeout: 45
      Policies:
        - AWSLambdaBasicExecutionRole
        - Statement:
            - Effect: Allow
              Action: lambda:InvokeFunction
              Resource: arn:aws:lambda:us-west-1:730335673618:function:SendUserConfirmationEmailLambdaFunction    
      Environment:
        Variables:
          MONGO_USER: "haydenfds"
          MONGO_PASS: "penisman"
          MONGO_CLUSTER: "cluster0.jr8nyfv.mongodb.net"


  ScrapeCourseInfoLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: ScrapeCourseInfoLambdaFunction
      Handler: app.main
      Runtime: python3.11
      CodeUri: scrape_course_info_lambda/
      MemorySize: 3000
      Timeout: 45

  ParseUrlLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: ParseUrlLambdaFunction
      Handler: parse_url/index.handler
      Runtime: nodejs18.x
      CodeUri: parse_url/
      MemorySize: 3000
      Timeout: 45


  SendUserConfirmationEmailLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: SendUserConfirmationEmailLambdaFunction
      Handler: app.main
      Runtime: python3.11
      CodeUri: send_confirmation_email_lambda/
      MemorySize: 1000
      Timeout: 45
      Environment:
        Variables:
          EMAIL_HOST: "smtp.gmail.com"
          EMAIL_PASS: "lowt sace zdvj ktbd"
          EMAIL_PORT: 587
          EMAIL_SENDER: "haydenfds@gmail.com"

  DoNothingLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: DoNothingLambdaFunction
      Handler: do_nothing_lambda/index.handler
      Runtime: nodejs18.x
      CodeUri: do_nothing_lambda/
      MemorySize: 1000
      Timeout: 45
      Policies:
        - AWSLambdaBasicExecutionRole

  FetchAllTerms:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: FetchAllTerms
      Handler: get_available_terms_lambda/index.handler
      Runtime: nodejs18.x
      CodeUri: get_available_terms_lambda/
      MemorySize: 1000
      Timeout: 45
      Policies:
        - AWSLambdaBasicExecutionRole

  FetchCoursesFromDeptAndTerm:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: FetchCourses
      Handler: fetch_courses_from_dept_and_term_lambda/index.handler
      Runtime: nodejs18.x
      CodeUri: fetch_courses_from_dept_and_term_lambda/
      MemorySize: 1000
      Timeout: 45
      Policies:
        - AWSLambdaBasicExecutionRole  